#!/bin/sh

# Hook to automatically deploy on every push
# Because why have a CI when you can have this?

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
	if [ "$remote_ref" = "refs/heads/master" ]; then
        mvn -Prelease clean deploy
	fi
done

exit 0
